package com.ybinsure.auth.model.data;

import java.io.Serializable;

public class DistrictDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.parent_id
     *
     * @mbg.generated
     */
    private Short parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.initial
     *
     * @mbg.generated
     */
    private String initial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.initials
     *
     * @mbg.generated
     */
    private String initials;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.pinyin
     *
     * @mbg.generated
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.sort
     *
     * @mbg.generated
     */
    private Byte sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_district.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.id
     *
     * @return the value of auth_district.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withId(Short id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.id
     *
     * @param id the value for auth_district.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.name
     *
     * @return the value of auth_district.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.name
     *
     * @param name the value for auth_district.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.parent_id
     *
     * @return the value of auth_district.parent_id
     *
     * @mbg.generated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withParentId(Short parentId) {
        this.setParentId(parentId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.parent_id
     *
     * @param parentId the value for auth_district.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.initial
     *
     * @return the value of auth_district.initial
     *
     * @mbg.generated
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withInitial(String initial) {
        this.setInitial(initial);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.initial
     *
     * @param initial the value for auth_district.initial
     *
     * @mbg.generated
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.initials
     *
     * @return the value of auth_district.initials
     *
     * @mbg.generated
     */
    public String getInitials() {
        return initials;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withInitials(String initials) {
        this.setInitials(initials);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.initials
     *
     * @param initials the value for auth_district.initials
     *
     * @mbg.generated
     */
    public void setInitials(String initials) {
        this.initials = initials == null ? null : initials.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.pinyin
     *
     * @return the value of auth_district.pinyin
     *
     * @mbg.generated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withPinyin(String pinyin) {
        this.setPinyin(pinyin);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.pinyin
     *
     * @param pinyin the value for auth_district.pinyin
     *
     * @mbg.generated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.suffix
     *
     * @return the value of auth_district.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withSuffix(String suffix) {
        this.setSuffix(suffix);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.suffix
     *
     * @param suffix the value for auth_district.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.code
     *
     * @return the value of auth_district.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withCode(String code) {
        this.setCode(code);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.code
     *
     * @param code the value for auth_district.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.sort
     *
     * @return the value of auth_district.sort
     *
     * @mbg.generated
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withSort(Byte sort) {
        this.setSort(sort);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.sort
     *
     * @param sort the value for auth_district.sort
     *
     * @mbg.generated
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.level
     *
     * @return the value of auth_district.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withLevel(Byte level) {
        this.setLevel(level);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.level
     *
     * @param level the value for auth_district.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_district.status
     *
     * @return the value of auth_district.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    public DistrictDO withStatus(Byte status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_district.status
     *
     * @param status the value for auth_district.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}