version: '2'
services:
  nginx:
    container_name: logback-nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
#    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dbperson

  redis:
    image: "redis:alpine"
    container_name: redisdb
    ports:
      - "6379:6379"

  logback-1:
    container_name: logback-1
    build: .
    restart: always
    depends_on:
      - mysqldb
      - redis
      - nginx

  logback-2:
    container_name: logback-2
    build: .
    restart: always
    depends_on:
      - mysqldb
      - redis
      - nginx