package com.ybinsure.auth.mapper.data;

import com.ybinsure.auth.model.data.DistrictDO;
import com.ybinsure.auth.model.data.DistrictDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistrictDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    long countByExample(DistrictDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    int deleteByExample(DistrictDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    int insert(DistrictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    int insertSelective(DistrictDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    List<DistrictDO> selectByExample(DistrictDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DistrictDO record, @Param("example") DistrictDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_district
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DistrictDO record, @Param("example") DistrictDOExample example);
}